on:
  push:
name: Generate markdown from JSDocs
jobs:
  run:
    name: Generate markdown
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
         ref: ${{ github.head_ref }}
      - run: sudo npm i -g jsdoc-to-markdown
      - run: ls
      - run: pwd
      - run: jsdoc2md index.js > documentation.md
      - run: rm -rf README.md
      - run: cat start.md documentation.md >> README.md
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Generate docs"
